version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-deps
      # Do NOT want `python/save-cache` here as it won't cache yamllint
      # - python/save-cache
      - run:
          name: Ensure schemas are up-to-date
          command: |
            ./scripts/fetch-schemas.py
            if [[ ! -z "$(git diff)" ]]; then
              echo "Schemas do not match schemas in mozilla-central!"
              exit 1
            fi
      - run:
          command: |
            touch *.json && make
          name: Build
      - run:
          command: make check
          name: Validate

workflows:
  main:
    jobs:
      - build-and-test
